/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visualAccesoSocios;

import gestionSocios.Socio;
import java.util.HashMap;
import java.util.ListIterator;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class ConsultaSocio2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaSocio
     */
    
      private HashMap<String,Socio> mapaSociosaux; //Referencia al ArrayList de publicaciones de la clase Biblioteca
    private ListIterator li; //Iterador para recorrer el ArrayList en ambas direcciones
    private Socio objSocio; //Referencia a un objeto de tipo publicacion del ArrayList
    
    public ConsultaSocio2(Socio s) {
        initComponents();
        objSocio=s;
        presentaDatosSocio(objSocio);
    }
     
     
    public void presentaDatosSocio(Socio s){
        
        
    cuadroDni.setText(s.getDni());
    cuadroCodigo.setText(s.getCodigoSocio());
    cuadroNombre.setText(s.getNombreSocio());
    FechaI.setValue(s.getFechaInscripcion());
    listaCategoria.getSelectedItem().equals(s.getCategoria());
    cuadroCategoria.setText(s.getCategoria());
    areaPrestamo.setText(s.getListadoPrestamos());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cuadroNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cuadroDni = new javax.swing.JTextField();
        listaCategoria = new javax.swing.JComboBox();
        cuadroCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPrestamo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cuadroCategoria = new javax.swing.JTextField();
        FechaI = new javax.swing.JSpinner();

        setClosable(true);
        setTitle("CONSULTA DE SOCIOS - -BIBLIOTECA UNIVERSITARIA");
        setToolTipText("");

        jLabel1.setText("DNI");

        cuadroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE Y APELLIDOS");

        cuadroDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroDniActionPerformed(evt);
            }
        });

        listaCategoria.setEditable(true);
        listaCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CATEGORIA", "PROFESOR", "ALUMNO" }));
        listaCategoria.setEnabled(false);
        listaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("CODIGO SOCIO");

        jLabel4.setText("FECHA INSCRIPCIÓN");

        areaPrestamo.setColumns(20);
        areaPrestamo.setRows(5);
        jScrollPane1.setViewportView(areaPrestamo);

        jLabel5.setText("PRESTAMOS");

        cuadroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroCategoriaActionPerformed(evt);
            }
        });

        FechaI.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1338846393892L), null, null, java.util.Calendar.DAY_OF_YEAR));
        FechaI.setEditor(new javax.swing.JSpinner.DateEditor(FechaI, "dd/MM/yyyy"));
        FechaI.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(listaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadroDni, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FechaI, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cuadroCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addComponent(cuadroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cuadroDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cuadroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(FechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuadroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroNombreActionPerformed

    private void cuadroDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroDniActionPerformed

    private void listaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaCategoriaActionPerformed

    private void cuadroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroCategoriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner FechaI;
    private javax.swing.JTextArea areaPrestamo;
    private javax.swing.JTextField cuadroCategoria;
    private javax.swing.JTextField cuadroCodigo;
    private javax.swing.JTextField cuadroDni;
    private javax.swing.JTextField cuadroNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listaCategoria;
    // End of variables declaration//GEN-END:variables
}
