/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import excepcionesBiblioteca.SociosException;
import gestionPublicaciones.Publicacion;
import gestionSocios.Socio;
import gestionSocios.UtilSocios;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class ConsultaSocio extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaSocio
     */
    
      private HashMap<String,Socio> mapaSociosaux; //Referencia al ArrayList de publicaciones de la clase Biblioteca
    private ListIterator li; //Iterador para recorrer el ArrayList en ambas direcciones
    private Socio objSocio; //Referencia a un objeto de tipo publicacion del ArrayList
    public ConsultaSocio() {
        initComponents();
        consultarTodo();
    }
     private void consultarTodo() {
        try {
            //referenciamos al ArrayList de la Biblioteca
             mapaSociosaux= UtilSocios.getMapaSocios();
             Collection<Socio>colec=mapaSociosaux.values();
    ArrayList<Socio> listaSocios=new ArrayList<>(colec);
            //creamos el iterador sobre el ArrayList
            li = listaSocios.listIterator();
            //si no hay publicaciones...
            if (listaSocios.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay Socios.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                ButtonSiguiente.setEnabled(false);
                ButtonAnterior.setEnabled(false);
              
                return;
            } else {
                ButtonSiguiente.setEnabled(true);
                ButtonAnterior.setEnabled(true);
              
            }
            //presentamos el primer producto
            if (li.hasNext()) {
                objSocio = (Socio) li.next();
            }
            if (objSocio != null) {
                presentaDatosSocio(objSocio);
            } else {
                JOptionPane.showMessageDialog(this, "No hay publicaciones.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
        }
    }//fin consultarTodo
     
    public void presentaDatosSocio(Socio s){
        campoA.setText(String.valueOf(UtilSocios.getA()));
        campoP.setText(String.valueOf(UtilSocios.getP()));
        
    cuadroDni.setText(s.getDni());
    cuadroCodigo.setText(s.getCodigoSocio());
    cuadroNombre.setText(s.getNombreSocio());
    FechaI.setValue(s.getFechaInscripcion());
    listaCategoria.getSelectedItem().equals(s.getCategoria());
    cuadroCategoria.setText(s.getCategoria());
    areaPrestamo.setText(s.getListadoPrestamos());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogoBajaSocio = new javax.swing.JDialog();
        cuadroCodigoBaja = new javax.swing.JTextField();
        jButtonConfirmarBajaSocio = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDialogoBuscarSocio = new javax.swing.JDialog();
        cuadroCodigoBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cuadroNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cuadroDni = new javax.swing.JTextField();
        listaCategoria = new javax.swing.JComboBox();
        cuadroCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPrestamo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        campoA = new javax.swing.JTextField();
        campoP = new javax.swing.JTextField();
        cuadroCategoria = new javax.swing.JTextField();
        FechaI = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        ButtonSiguiente = new javax.swing.JButton();
        ButtonAnterior = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonBuscarSocio = new javax.swing.JButton();
        jButtonBajaSocio = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();

        jDialogoBajaSocio.setTitle("BAJA SOCIO");
        jDialogoBajaSocio.setAlwaysOnTop(true);
        jDialogoBajaSocio.setMinimumSize(new java.awt.Dimension(500, 500));

        cuadroCodigoBaja.setToolTipText("CODIGO DEL SOCIO A ELIMINAR");

        jButtonConfirmarBajaSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Accept16.png"))); // NOI18N
        jButtonConfirmarBajaSocio.setText("CONFIRMAR BAJA SOCIO");
        jButtonConfirmarBajaSocio.setToolTipText("REALIZA LA BAJA DEL SOCIO");
        jButtonConfirmarBajaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarBajaSocioActionPerformed(evt);
            }
        });

        jLabel6.setText("CODIGO A ELIMINAR");

        jLabel7.setText("INTRODUZCA O VERIFIQUE EL CODIGO DEL SOCIO QUE QUIERE ELIMINAR");

        javax.swing.GroupLayout jDialogoBajaSocioLayout = new javax.swing.GroupLayout(jDialogoBajaSocio.getContentPane());
        jDialogoBajaSocio.getContentPane().setLayout(jDialogoBajaSocioLayout);
        jDialogoBajaSocioLayout.setHorizontalGroup(
            jDialogoBajaSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogoBajaSocioLayout.createSequentialGroup()
                .addGroup(jDialogoBajaSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogoBajaSocioLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cuadroCodigoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogoBajaSocioLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(jDialogoBajaSocioLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonConfirmarBajaSocio)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jDialogoBajaSocioLayout.setVerticalGroup(
            jDialogoBajaSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogoBajaSocioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addGroup(jDialogoBajaSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroCodigoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(55, 55, 55)
                .addComponent(jButtonConfirmarBajaSocio)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jDialogoBuscarSocio.setTitle("DIALOG DE BUSQUEDA");
        jDialogoBuscarSocio.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel8.setText("codigo a buscar");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Find32.png"))); // NOI18N
        jButton1.setText("BÚSQUEDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("INTRODUZCA EL CODIGO DE LA PUBLICACION QUE DESEA BUSCAR");

        javax.swing.GroupLayout jDialogoBuscarSocioLayout = new javax.swing.GroupLayout(jDialogoBuscarSocio.getContentPane());
        jDialogoBuscarSocio.getContentPane().setLayout(jDialogoBuscarSocioLayout);
        jDialogoBuscarSocioLayout.setHorizontalGroup(
            jDialogoBuscarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogoBuscarSocioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addComponent(cuadroCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jDialogoBuscarSocioLayout.createSequentialGroup()
                .addGroup(jDialogoBuscarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogoBuscarSocioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9))
                    .addGroup(jDialogoBuscarSocioLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jDialogoBuscarSocioLayout.setVerticalGroup(
            jDialogoBuscarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogoBuscarSocioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(jDialogoBuscarSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        setClosable(true);
        setTitle("CONSULTA DE SOCIOS - -BIBLIOTECA UNIVERSITARIA");
        setToolTipText("");

        jLabel1.setText("DNI");

        cuadroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("NOMBRE Y APELLIDOS");

        cuadroDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroDniActionPerformed(evt);
            }
        });

        listaCategoria.setEditable(true);
        listaCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CATEGORIA", "PROFESOR", "ALUMNO" }));
        listaCategoria.setEnabled(false);
        listaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("CODIGO SOCIO");

        jLabel4.setText("FECHA INSCRIPCIÓN");

        areaPrestamo.setColumns(20);
        areaPrestamo.setRows(5);
        jScrollPane1.setViewportView(areaPrestamo);

        jLabel5.setText("PRESTAMOS");

        cuadroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroCategoriaActionPerformed(evt);
            }
        });

        FechaI.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1338846393892L), null, null, java.util.Calendar.DAY_OF_YEAR));
        FechaI.setEditor(new javax.swing.JSpinner.DateEditor(FechaI, "dd/MM/yyyy"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(listaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoA, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(campoP))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuadroDni, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FechaI, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cuadroCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addComponent(cuadroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuadroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cuadroDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cuadroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cuadroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(FechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(campoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        ButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/siguiente.gif"))); // NOI18N
        ButtonSiguiente.setToolTipText("PUBLICACIÓN SIGUIENTE>>");
        ButtonSiguiente.setOpaque(false);
        ButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSiguienteActionPerformed(evt);
            }
        });

        ButtonAnterior.setForeground(new java.awt.Color(51, 51, 51));
        ButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/anterior.gif"))); // NOI18N
        ButtonAnterior.setToolTipText("<<PUBLICACIÓN ANTERIOR");
        ButtonAnterior.setOpaque(false);
        ButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(ButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        jButtonBuscarSocio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBuscarSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Find32.png"))); // NOI18N
        jButtonBuscarSocio.setText("BUSCAR");
        jButtonBuscarSocio.setToolTipText("BUSQUEDA POR CODIGO DE SOCIO");
        jButtonBuscarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSocioActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBuscarSocio);

        jButtonBajaSocio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonBajaSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Deleteuser32.png"))); // NOI18N
        jButtonBajaSocio.setText("BAJA");
        jButtonBajaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaSocioActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBajaSocio);

        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Refresh32.png"))); // NOI18N
        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.setToolTipText("ACTUALIZA LAS NUEVAS ALTAS INTRODUCIDAS");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonActualizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuadroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroNombreActionPerformed

    private void cuadroDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroDniActionPerformed

    private void listaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaCategoriaActionPerformed

    private void jButtonBuscarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSocioActionPerformed
       jDialogoBuscarSocio.setVisible(true);
       jDialogoBuscarSocio.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButtonBuscarSocioActionPerformed

    private void ButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSiguienteActionPerformed
        // TODO add your handling code here:
        if (li.hasNext()) {
            objSocio = (Socio) li.next();
            if (objSocio != null) {
                presentaDatosSocio(objSocio);
            } else {
                JOptionPane.showMessageDialog(this, "No hay mas socios en la Biblioteca.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_ButtonSiguienteActionPerformed

    private void ButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnteriorActionPerformed
        // TODO add your handling code here:
        if (li.hasPrevious()) {
            objSocio = (Socio) li.previous();
            if (objSocio != null) {
                presentaDatosSocio(objSocio);
            } else {
                JOptionPane.showMessageDialog(this, "No hay publicaciones.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_ButtonAnteriorActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        consultarTodo();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonConfirmarBajaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarBajaSocioActionPerformed
        try {
            // TODO add your handling code here:
            String codigoBaja=cuadroCodigoBaja.getText();
            UtilSocios.bajaSocio(codigoBaja);
            JOptionPane.showMessageDialog(jDialogoBajaSocio, "Baja del socio con codigo " +codigoBaja,"INFORMACION DE LA BAJA", JOptionPane.INFORMATION_MESSAGE);
        } catch (SociosException se) {
            JOptionPane.showMessageDialog(jDialogoBajaSocio, "Error, al dar la baja" + se.toString(), "INFORMACION DE LA BAJA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConfirmarBajaSocioActionPerformed

    private void jButtonBajaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaSocioActionPerformed
        // TODO add your handling code here:
        jDialogoBajaSocio.setVisible(true);
        jDialogoBajaSocio.setLocationRelativeTo(this);
        cuadroCodigoBaja.setText(objSocio.getCodigoSocio());
    }//GEN-LAST:event_jButtonBajaSocioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
           String cod= cuadroCodigoBuscar.getText();
           Socio s1=UtilSocios.buscarSocio(cod);
           presentaDatosSocio(s1);
           JOptionPane.showMessageDialog(jDialogoBuscarSocio, "USUARIO ENCONTRADO","INFORMACION BÚSQUEDA", JOptionPane.INFORMATION_MESSAGE);
           jDialogoBuscarSocio.setVisible(false);
           
        } catch (SociosException se) {
            JOptionPane.showMessageDialog(jDialogoBajaSocio, "Error, en búsqueda" + se.toString(), "INFORMACION DE LA Búsqueda", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cuadroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroCategoriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnterior;
    private javax.swing.JButton ButtonSiguiente;
    private javax.swing.JSpinner FechaI;
    private javax.swing.JTextArea areaPrestamo;
    private javax.swing.JTextField campoA;
    private javax.swing.JTextField campoP;
    private javax.swing.JTextField cuadroCategoria;
    private javax.swing.JTextField cuadroCodigo;
    private javax.swing.JTextField cuadroCodigoBaja;
    private javax.swing.JTextField cuadroCodigoBuscar;
    private javax.swing.JTextField cuadroDni;
    private javax.swing.JTextField cuadroNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBajaSocio;
    private javax.swing.JButton jButtonBuscarSocio;
    private javax.swing.JButton jButtonConfirmarBajaSocio;
    private javax.swing.JDialog jDialogoBajaSocio;
    private javax.swing.JDialog jDialogoBuscarSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listaCategoria;
    // End of variables declaration//GEN-END:variables
}
