/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import excepcionesBiblioteca.BibliotecaException;
import gestionPublicaciones.Biblioteca;
import gestionPublicaciones.Publicacion;
import gestionSocios.UtilSocios;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class GuiPublicaciones extends javax.swing.JFrame {

    /**
     * Creates new form GuiPublicaciones
     */
    private JFrame principal;
    public GuiPublicaciones(JFrame ventana) {
        initComponents();
        principal=ventana;
        principal.setVisible(false);
        UtilSocios.cargarDatosSocios();
        Biblioteca.cargarDatos();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        jDialogValidar.setLocationRelativeTo(this);
        jDialogValidar.setVisible(true);
        jMenuBar1.setVisible(false);
        
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogValidar = new javax.swing.JDialog();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jDialogoBajaPublicacion = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        cuadroCodigoBaja = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPublicaciones = new javax.swing.JMenu();
        jMenuAlta = new javax.swing.JMenuItem();
        jMenuItemBaja = new javax.swing.JMenuItem();
        jMenuItemConsulta = new javax.swing.JMenuItem();
        jMenuSocios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jDialogValidar.setTitle("VALIDAR ADMINISTRADOR");
        jDialogValidar.setAlwaysOnTop(true);
        jDialogValidar.setLocationByPlatform(true);
        jDialogValidar.setMinimumSize(new java.awt.Dimension(400, 400));
        jDialogValidar.setType(java.awt.Window.Type.UTILITY);
        jDialogValidar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogValidarWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialogValidarWindowClosed(evt);
            }
        });

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/User32.png"))); // NOI18N
        jLabel87.setText("Usuario");

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Key32.png"))); // NOI18N
        jLabel88.setText("Contraseña");
        jLabel88.setToolTipText("Contraseña Administrador");

        jTextUsuario.setToolTipText("Login usuario administrador");

        jPassword.setToolTipText("Contraseña administrador");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Accept32.png"))); // NOI18N
        jButton4.setText("ACEPTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("VALIDAR ADMINISTRADOR");

        javax.swing.GroupLayout jDialogValidarLayout = new javax.swing.GroupLayout(jDialogValidar.getContentPane());
        jDialogValidar.getContentPane().setLayout(jDialogValidarLayout);
        jDialogValidarLayout.setHorizontalGroup(
            jDialogValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogValidarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jDialogValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDialogValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jDialogValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextUsuario)
                        .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogValidarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(132, 132, 132))
        );
        jDialogValidarLayout.setVerticalGroup(
            jDialogValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogValidarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jDialogValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(40, 40, 40))
        );

        jDialogValidar.getAccessibleContext().setAccessibleParent(jDesktopPane1);

        jDialogoBajaPublicacion.setTitle("BAJA POR CODIGO");
        jDialogoBajaPublicacion.setMinimumSize(new java.awt.Dimension(500, 500));

        jButton1.setText("Dar de Baja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Código de la publicación:");

        jLabel2.setText("INTRODUZCA EL CODIGO DE LA PUBLICACIÓN QUE QUIERE DAR DE BAJA");

        javax.swing.GroupLayout jDialogoBajaPublicacionLayout = new javax.swing.GroupLayout(jDialogoBajaPublicacion.getContentPane());
        jDialogoBajaPublicacion.getContentPane().setLayout(jDialogoBajaPublicacionLayout);
        jDialogoBajaPublicacionLayout.setHorizontalGroup(
            jDialogoBajaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogoBajaPublicacionLayout.createSequentialGroup()
                .addGroup(jDialogoBajaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogoBajaPublicacionLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cuadroCodigoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogoBajaPublicacionLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1))
                    .addGroup(jDialogoBajaPublicacionLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jDialogoBajaPublicacionLayout.setVerticalGroup(
            jDialogoBajaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogoBajaPublicacionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addGroup(jDialogoBajaPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroCodigoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA UNIVERSITARIA");
        setBackground(new java.awt.Color(153, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuPublicaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Publicacion32.png"))); // NOI18N
        jMenuPublicaciones.setText("Gestion Publicaciones");
        jMenuPublicaciones.setToolTipText("Altas, Bajas y Búsquedas");
        jMenuPublicaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuAlta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Addfile32.png"))); // NOI18N
        jMenuAlta.setText("Alta Publicación");
        jMenuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaActionPerformed(evt);
            }
        });
        jMenuPublicaciones.add(jMenuAlta);

        jMenuItemBaja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Deletefile32.png"))); // NOI18N
        jMenuItemBaja.setText("Baja Publicación por codigo");
        jMenuItemBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajaActionPerformed(evt);
            }
        });
        jMenuPublicaciones.add(jMenuItemBaja);

        jMenuItemConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItemConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Refresh32.png"))); // NOI18N
        jMenuItemConsulta.setText("Consulta, Préstamo y Modificación");
        jMenuItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaActionPerformed(evt);
            }
        });
        jMenuPublicaciones.add(jMenuItemConsulta);

        jMenuBar1.add(jMenuPublicaciones);

        jMenuSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Groupusers32.png"))); // NOI18N
        jMenuSocios.setText("Gestion Socios");
        jMenuSocios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSociosActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Adduser32.png"))); // NOI18N
        jMenuItem1.setText("Alta Socio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/User32.png"))); // NOI18N
        jMenuItem2.setText("Consulta socios, Baja, Busqueda");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSocios.add(jMenuItem2);

        jMenuBar1.add(jMenuSocios);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Home.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Back32.png"))); // NOI18N
        jMenuItem3.setText("Volver a inicio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaActionPerformed
        // TODO add your handling code here:
         VentanaAltaPublicaciones va3 = new VentanaAltaPublicaciones();
        this.jDesktopPane1.add(va3);
        
        va3.show();
    }//GEN-LAST:event_jMenuAltaActionPerformed

    private void jMenuItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaActionPerformed
        // TODO add your handling code here:
         VentanaModificacion vm=new VentanaModificacion();
        vm.setVisible(true);
        this.jDesktopPane1.add(vm);
        vm.show();
    }//GEN-LAST:event_jMenuItemConsultaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       if ((jTextUsuario.getText().equals("admin"))&&(jPassword.getText().equals("1234"))){
           jMenuBar1.setVisible(true);
           jDialogValidar.setVisible(false);
           
    
    }else{
        JOptionPane.showMessageDialog(jDialogValidar,"\nCONTRASEÑA O USUARIO INCORRECTO"+JOptionPane.INFORMATION_MESSAGE);
       jDialogValidar.setVisible(true);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jDialogValidarWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogValidarWindowClosed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jDialogValidarWindowClosed

    private void jDialogValidarWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogValidarWindowClosing
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jDialogValidarWindowClosing

    private void jMenuSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSociosActionPerformed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_jMenuSociosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        GestionSocios gs = new GestionSocios();
         gs.setVisible(true);
        this.jDesktopPane1.add(gs);
        gs.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ConsultaSocio cs=new ConsultaSocio();
        cs.setVisible(true);
        this.jDesktopPane1.add(cs);
        cs.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        UtilSocios.guardarDatosSocios();
        Biblioteca.guardarDatos();
    }//GEN-LAST:event_formWindowClosing

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       
       
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
           String codigoBaja= cuadroCodigoBaja.getText();
           Publicacion p=Biblioteca.busquedaCodigo(codigoBaja);
           Biblioteca.bajaProducto(p);
           cuadroCodigoBaja.setText("");
           JOptionPane.showMessageDialog(jDialogoBajaPublicacion,"\nBaja con codigo: "+codigoBaja+" realizada con exito"+JOptionPane.INFORMATION_MESSAGE);
        } catch (BibliotecaException ex) {
            JOptionPane.showMessageDialog(jDialogoBajaPublicacion,"Error en la baja"+ex.toString(),"Mensaje Bajas Publicaciones", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBajaActionPerformed
        // TODO add your handling code here:
        jDialogoBajaPublicacion.setVisible(true);
        jDialogoBajaPublicacion.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItemBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPublicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
       /*java.awt.EventQueue.invokeLater(new Runnable() {

           public void run() {
                new GuiPublicaciones().setVisible(true);
            }
        });*/
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cuadroCodigoBaja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialogValidar;
    private javax.swing.JDialog jDialogoBajaPublicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAlta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemBaja;
    private javax.swing.JMenuItem jMenuItemConsulta;
    private javax.swing.JMenu jMenuPublicaciones;
    private javax.swing.JMenu jMenuSocios;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
