/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import excepcionesBiblioteca.BibliotecaException;
import excepcionesBiblioteca.PublicacionException;
import gestionPublicaciones.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.Date;
import java.util.ListIterator;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class VentanaAltaPublicaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form ventanaAlta3
     */
    private ArrayList<Publicacion> arrayBiblioaux; //Referencia al ArrayList de publicaciones de la clase Biblioteca
    private ListIterator li; //Iterador para recorrer el ArrayList en ambas direcciones
    private Publicacion objPublicacion; //Referencia a un objeto de tipo publicacion del ArrayList
    
    public VentanaAltaPublicaciones() {
        initComponents();
        this.setLocation(WIDTH, WIDTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPublicacion = new javax.swing.JPanel();
        cuadroTitulo = new javax.swing.JTextField();
        cuadroPublicacion = new javax.swing.JTextField();
        cuadroAutores = new javax.swing.JTextField();
        cuadroIsbn = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaObservaciones = new javax.swing.JTextArea();
        jLabel64 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        comboBoxPublicaciones = new javax.swing.JComboBox();
        jLabel62 = new javax.swing.JLabel();
        cuadroPaginas = new javax.swing.JTextField();
        cuadroCodigo = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        cuadroColeccion = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        cuadroMateria = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        Fecha = new javax.swing.JSpinner();
        jPanelTiposFondo = new javax.swing.JPanel();
        jPanelProyecto = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        cuadroTribunalP = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        cuadroCalificacionP = new javax.swing.JTextField();
        cuadroEntidadP = new javax.swing.JTextField();
        cuadroDepartamentoP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cuadroTitulacionP = new javax.swing.JTextField();
        FechaLectura = new javax.swing.JSpinner();
        jPanelTesis = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        cuadroTribunalT = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        cuadroCalificacionT = new javax.swing.JTextField();
        cuadroEntidadT = new javax.swing.JTextField();
        cuadroDepartamentoT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroProgramaT = new javax.swing.JTextArea();
        FechaLecturaT = new javax.swing.JSpinner();
        jPanelRevistas = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        cuadroLocalizacionR = new javax.swing.JTextField();
        cuadroNumero = new javax.swing.JTextField();
        cuadroVolumen = new javax.swing.JTextField();
        FechaRevista = new javax.swing.JSpinner();
        listaPeriodicidad = new javax.swing.JComboBox();
        jPanelLibro = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        cuadroEditorial = new javax.swing.JTextField();
        jLabel83 = new javax.swing.JLabel();
        cuadroLocalizacion = new javax.swing.JTextField();
        cuadroContenido = new javax.swing.JTextField();
        cuadroEdicion = new javax.swing.JTextField();
        cuadroLocalidad = new javax.swing.JTextField();
        jPanelImagen = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jButtonBuscarIcon = new javax.swing.JButton();
        jLabelRuta = new javax.swing.JLabel();
        jPanelControl = new javax.swing.JPanel();
        jButtonAlta = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("BIBLOTECA UNIVERSITARIA - - ALTA DE PUBLICACIONES");
        setToolTipText("ALTA DE PUBLICACIONES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/book.png"))); // NOI18N

        jPanelPublicacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PUBLICACION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanelPublicacion.setToolTipText("DATOS GENERALES PUBLICACIÓN");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel60.setText("Codigo");

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel61.setText("ISBN");

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel65.setText("Materia");

        areaObservaciones.setColumns(20);
        areaObservaciones.setRows(5);
        jScrollPane3.setViewportView(areaObservaciones);

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel64.setText("Páginas");

        jLabel63.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel63.setText("Autores");

        comboBoxPublicaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libros", "Revistas", "Proyectos", "Tesis Doctorales" }));
        comboBoxPublicaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxPublicacionesItemStateChanged(evt);
            }
        });
        comboBoxPublicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPublicacionesActionPerformed(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel62.setText("Titulo");

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel68.setText("Fecha publicación:");

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel67.setText("Observaciones:");

        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel66.setText("Colección");

        Fecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1338846393892L), new java.util.Date(81420000L), new java.util.Date(), java.util.Calendar.DAY_OF_YEAR));
        Fecha.setEditor(new javax.swing.JSpinner.DateEditor(Fecha, "dd/MM/yyyy"));

        javax.swing.GroupLayout jPanelPublicacionLayout = new javax.swing.GroupLayout(jPanelPublicacion);
        jPanelPublicacion.setLayout(jPanelPublicacionLayout);
        jPanelPublicacionLayout.setHorizontalGroup(
            jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBoxPublicaciones, 0, 1, Short.MAX_VALUE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cuadroCodigo)
                        .addComponent(cuadroTitulo)
                        .addComponent(cuadroAutores)
                        .addComponent(cuadroIsbn)
                        .addComponent(cuadroPaginas)
                        .addComponent(cuadroMateria)
                        .addComponent(cuadroColeccion)
                        .addComponent(jScrollPane3)
                        .addComponent(cuadroPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPublicacionLayout.setVerticalGroup(
            jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuadroPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPublicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(cuadroIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadroAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPublicacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadroMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadroColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPublicacionLayout.createSequentialGroup()
                        .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(126, 126, 126))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanelTiposFondo.setBackground(new java.awt.Color(204, 255, 255));
        jPanelTiposFondo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(153, 153, 153)));
        jPanelTiposFondo.setForeground(new java.awt.Color(204, 255, 255));
        jPanelTiposFondo.setToolTipText("");
        jPanelTiposFondo.setLayout(new java.awt.CardLayout());

        jPanelProyecto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PROYECTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanelProyecto.setToolTipText("DATOS DEL PROYECTO");

        jLabel111.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel111.setText("Tribunal");

        jLabel112.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel112.setText("Departamento");

        jLabel113.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel113.setText("Entidad");

        jLabel114.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel114.setText("Calificación");

        jLabel115.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel115.setText("Fecha lectura");

        cuadroEntidadP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroEntidadPActionPerformed(evt);
            }
        });

        cuadroDepartamentoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroDepartamentoPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Titulación");

        FechaLectura.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1338847422650L), new java.util.Date(-3420000L), new java.util.Date(1359586860000L), java.util.Calendar.DAY_OF_MONTH));
        FechaLectura.setEditor(new javax.swing.JSpinner.DateEditor(FechaLectura, "dd/MM/yyyy"));

        javax.swing.GroupLayout jPanelProyectoLayout = new javax.swing.GroupLayout(jPanelProyecto);
        jPanelProyecto.setLayout(jPanelProyectoLayout);
        jPanelProyectoLayout.setHorizontalGroup(
            jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel115)
                    .addComponent(jLabel111)
                    .addComponent(jLabel112)
                    .addComponent(jLabel113)
                    .addComponent(jLabel114))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuadroTribunalP, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(cuadroDepartamentoP)
                    .addComponent(cuadroEntidadP)
                    .addComponent(cuadroCalificacionP)
                    .addComponent(cuadroTitulacionP)
                    .addComponent(FechaLectura))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelProyectoLayout.setVerticalGroup(
            jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel111)
                    .addComponent(cuadroTribunalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel112)
                    .addComponent(cuadroDepartamentoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel113)
                    .addComponent(cuadroEntidadP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel114)
                    .addComponent(cuadroCalificacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel115)
                    .addComponent(FechaLectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cuadroTitulacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanelTiposFondo.add(jPanelProyecto, "card7");

        jPanelTesis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS TESIS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanelTesis.setToolTipText("DATOS DE LA TESIS");

        jLabel101.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel101.setText("Tribunal");

        jLabel102.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel102.setText("Departamento");

        jLabel103.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel103.setText("Entidad");

        jLabel104.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel104.setText("Calificación");

        jLabel105.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel105.setText("Fecha lectura");

        cuadroEntidadT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroEntidadTActionPerformed(evt);
            }
        });

        cuadroDepartamentoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroDepartamentoTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Programa");

        cuadroProgramaT.setColumns(20);
        cuadroProgramaT.setRows(5);
        jScrollPane1.setViewportView(cuadroProgramaT);

        FechaLecturaT.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1338847422650L), new java.util.Date(-3420000L), new java.util.Date(1359586860000L), java.util.Calendar.DAY_OF_MONTH));
        FechaLecturaT.setEditor(new javax.swing.JSpinner.DateEditor(FechaLecturaT, "dd/MM/yyyy"));

        javax.swing.GroupLayout jPanelTesisLayout = new javax.swing.GroupLayout(jPanelTesis);
        jPanelTesis.setLayout(jPanelTesisLayout);
        jPanelTesisLayout.setHorizontalGroup(
            jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTesisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel101)
                    .addComponent(jLabel102)
                    .addComponent(jLabel103)
                    .addComponent(jLabel104)
                    .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel105)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuadroTribunalT)
                    .addComponent(cuadroDepartamentoT)
                    .addComponent(cuadroEntidadT)
                    .addComponent(cuadroCalificacionT)
                    .addComponent(jScrollPane1)
                    .addComponent(FechaLecturaT, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelTesisLayout.setVerticalGroup(
            jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTesisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel101)
                    .addComponent(cuadroTribunalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel102)
                    .addComponent(cuadroDepartamentoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel103)
                    .addComponent(cuadroEntidadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel104)
                    .addComponent(cuadroCalificacionT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel105)
                    .addComponent(FechaLecturaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanelTiposFondo.add(jPanelTesis, "card7");

        jPanelRevistas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS REVISTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanelRevistas.setToolTipText("DATOS DE LA REVISTA");

        jLabel84.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel84.setText("Periodicidad");

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel87.setText("Volumen");

        jLabel88.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel88.setText("Número");

        jLabel89.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel89.setText("Año Disponible");

        jLabel90.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel90.setText("Localizacion");

        cuadroNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroNumeroActionPerformed(evt);
            }
        });

        cuadroVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroVolumenActionPerformed(evt);
            }
        });

        FechaRevista.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.YEAR));
        FechaRevista.setEditor(new javax.swing.JSpinner.DateEditor(FechaRevista, "yyyy"));

        listaPeriodicidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "TRIMESTRAL", "SEMESTRAL", "ANUAL" }));

        javax.swing.GroupLayout jPanelRevistasLayout = new javax.swing.GroupLayout(jPanelRevistas);
        jPanelRevistas.setLayout(jPanelRevistasLayout);
        jPanelRevistasLayout.setHorizontalGroup(
            jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRevistasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel90)
                    .addComponent(jLabel84)
                    .addComponent(jLabel87)
                    .addComponent(jLabel88)
                    .addComponent(jLabel89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuadroVolumen)
                    .addComponent(cuadroNumero)
                    .addComponent(cuadroLocalizacionR, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(FechaRevista)
                    .addComponent(listaPeriodicidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelRevistasLayout.setVerticalGroup(
            jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRevistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(listaPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(cuadroVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel88)
                    .addComponent(cuadroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel89)
                    .addComponent(FechaRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRevistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel90)
                    .addComponent(cuadroLocalizacionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jPanelTiposFondo.add(jPanelRevistas, "card7");

        jPanelLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS LIBRO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));
        jPanelLibro.setToolTipText("DATOS DEL LIBRO");

        jLabel79.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel79.setText("Editorial");

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel80.setText("Localidad");

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel81.setText("Edicion");

        jLabel82.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel82.setText("Contenido");

        jLabel83.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel83.setText("Localizacion");

        cuadroEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroEdicionActionPerformed(evt);
            }
        });

        cuadroLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadroLocalidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLibroLayout = new javax.swing.GroupLayout(jPanelLibro);
        jPanelLibro.setLayout(jPanelLibroLayout);
        jPanelLibroLayout.setHorizontalGroup(
            jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLibroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel83)
                    .addComponent(jLabel79)
                    .addComponent(jLabel80)
                    .addComponent(jLabel81)
                    .addComponent(jLabel82))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuadroEditorial)
                    .addComponent(cuadroLocalidad)
                    .addComponent(cuadroEdicion)
                    .addComponent(cuadroContenido)
                    .addComponent(cuadroLocalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanelLibroLayout.setVerticalGroup(
            jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79)
                    .addComponent(cuadroEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(cuadroLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(cuadroEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(cuadroContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel83)
                    .addComponent(cuadroLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jPanelTiposFondo.add(jPanelLibro, "card4");

        jPanelImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMAGEN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelImagen.setToolTipText("IMAGEN");

        javax.swing.GroupLayout jPanelImagenLayout = new javax.swing.GroupLayout(jPanelImagen);
        jPanelImagen.setLayout(jPanelImagenLayout);
        jPanelImagenLayout.setHorizontalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelImagenLayout.setVerticalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenLayout.createSequentialGroup()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonBuscarIcon.setBackground(new java.awt.Color(204, 204, 204));
        jButtonBuscarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/camara.gif"))); // NOI18N
        jButtonBuscarIcon.setText("Examinar");
        jButtonBuscarIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarIconActionPerformed(evt);
            }
        });

        jLabelRuta.setBackground(new java.awt.Color(204, 255, 255));
        jLabelRuta.setText("Ruta");
        jLabelRuta.setToolTipText("Ruta de la imagen");
        jLabelRuta.setAutoscrolls(true);

        jPanelControl.setLayout(new java.awt.GridLayout(2, 0));

        jButtonAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/Addfile32.png"))); // NOI18N
        jButtonAlta.setText("ALTA DE LA PUBLICACIÓN");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });
        jPanelControl.add(jButtonAlta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTiposFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRuta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTiposFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuadroEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroEdicionActionPerformed

    private void cuadroLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroLocalidadActionPerformed

    private void cuadroNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroNumeroActionPerformed

    private void cuadroVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroVolumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroVolumenActionPerformed

    private void cuadroEntidadTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroEntidadTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroEntidadTActionPerformed

    private void cuadroDepartamentoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroDepartamentoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroDepartamentoTActionPerformed

    private void cuadroEntidadPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroEntidadPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroEntidadPActionPerformed

    private void cuadroDepartamentoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadroDepartamentoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroDepartamentoPActionPerformed

    private void comboBoxPublicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPublicacionesActionPerformed
        // TODO add your handling code here:
       String Lista;
        Lista = (String) comboBoxPublicaciones.getSelectedItem();
        if(Lista.equals("Libros")){
            jPanelLibro.setVisible(true);
            jPanelProyecto.setVisible(false);
            jPanelRevistas.setVisible(false);
            jPanelTesis.setVisible(false);
            cuadroPublicacion.setText("Libro");
            }
        if(Lista.equals("Proyectos")){
            jPanelProyecto.setVisible(true);
            jPanelRevistas.setVisible(false);
            jPanelTesis.setVisible(false);
            jPanelLibro.setVisible(false);
            cuadroPublicacion.setText("Proyecto");
        }
         if(Lista.equals("Tesis Doctorales")){
            jPanelProyecto.setVisible(false);
            jPanelProyecto.setVisible(false);
            jPanelRevistas.setVisible(false);
            jPanelTesis.setVisible(true);
            cuadroPublicacion.setText("Tesis Doctoral");
        }
        
         if(Lista.equals("Revistas")){
            jPanelProyecto.setVisible(false);
            jPanelLibro.setVisible(false);
            jPanelRevistas.setVisible(true);
            jPanelTesis.setVisible(false);
            cuadroPublicacion.setText("Revista");
        }
    }//GEN-LAST:event_comboBoxPublicacionesActionPerformed

    private void comboBoxPublicacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxPublicacionesItemStateChanged
        // TODO add your handling code here:
        if (comboBoxPublicaciones.equals("Libro")) {
            jPanelLibro.setVisible(true);
        }
    }//GEN-LAST:event_comboBoxPublicacionesItemStateChanged

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        // TODO add your handling code here:
        String codigo=cuadroCodigo.getText();
        String isbn=cuadroIsbn.getText();
        String autores=cuadroAutores.getText();
        String titulo=cuadroTitulo.getText();
        String coleccion=cuadroColeccion.getText();
        String observaciones=areaObservaciones.getText();
        String materia=cuadroMateria.getText();
        Date FechaP=(Date)Fecha.getValue();
        String strPag=cuadroPaginas.getText();
        String nombreImagen=(codigo+".jpg");
         
        


 //copiamos mediante la ruta y el nombre, la imagen en el directorio <imagenes> (desde donde luego se visualizara en las consultas)
	try{
 
 String ruta=jLabelRuta.getText();
            FileOutputStream fos;
            try (FileInputStream fis = new FileInputStream(ruta)) {
                fos = new FileOutputStream("imagenes/"+nombreImagen+"");
                FileChannel inChannel = fis.getChannel();
                FileChannel outChannel = fos.getChannel();
                inChannel.transferTo(0, inChannel.size(), outChannel);
            }
fos.close();
 }catch (IOException ioe) {
 System.err.println("Error al Generar Copia");
 }
        
        try{
            
        if (cuadroPublicacion.getText().equals("Libro")){
            int paginas=Integer.parseInt(strPag);
        String editorial=cuadroEditorial.getText();
        String edicion=cuadroEdicion.getText();
        String localizacion=cuadroLocalizacion.getText();
        String localidad=cuadroLocalidad.getText();
        String contenido=cuadroContenido.getText();
        Publicacion libro=new Libro(editorial, localidad, contenido, edicion, localizacion, codigo,
                isbn, titulo, autores,FechaP, paginas, materia,coleccion,observaciones, nombreImagen);
        Biblioteca.altaPublicacion(libro);
        
        }
        if (cuadroPublicacion.getText().equals("Revista")){
            int paginas=Integer.parseInt(strPag);
        String periodicidad=listaPeriodicidad.getSelectedItem().toString();
        int volumen=Integer.parseInt(cuadroVolumen.getText());
        String localizacion=cuadroLocalizacionR.getText();
        int numero=Integer.parseInt(cuadroNumero.getText());
        Date anyo=(Date)FechaRevista.getValue();
        
        Publicacion revista=new Revista(periodicidad, volumen, numero, anyo,
                localizacion, codigo, isbn,titulo, autores, FechaP, paginas,
                materia, coleccion,observaciones, nombreImagen);
        Biblioteca.altaPublicacion(revista);
        }
        
        if (cuadroPublicacion.getText().equals("Tesis Doctoral")){
            int paginas=Integer.parseInt(strPag);
        String tribunal=cuadroTribunalT.getText();
        Date fechaLectura=(Date)FechaLecturaT.getValue();
        String departamento=cuadroDepartamentoT.getText();
        String entidad=cuadroEntidadT.getText();
        String programa=cuadroProgramaT.getText();
        double calificacion=Double.parseDouble(cuadroCalificacionT.getText());
        
        Publicacion tesis=new Tesis(programa, tribunal, entidad, departamento, calificacion, fechaLectura, codigo, isbn,
        titulo, autores, FechaP, paginas, materia, coleccion, observaciones, nombreImagen);
        Biblioteca.altaPublicacion(tesis);
        }
        
          if (cuadroPublicacion.getText().equals("Proyecto")){
            int paginas=Integer.parseInt(strPag);
        String tribunal=cuadroTribunalP.getText();
        Date fechaLectura=(Date)FechaLectura.getValue();
        String departamento=cuadroDepartamentoP.getText();
        String entidad=cuadroEntidadP.getText();
        String titulacion=cuadroTitulacionP.getText();
        double calificacion=Double.parseDouble(cuadroCalificacionP.getText());
        
        Publicacion proyecto=new Proyecto(titulacion, tribunal, entidad, departamento, calificacion, fechaLectura, codigo, isbn,
        titulo, autores, FechaP, paginas, materia, coleccion, observaciones, nombreImagen);
        Biblioteca.altaPublicacion(proyecto);
        }
        
        
        
        JOptionPane.showMessageDialog(this,"\nALTA REALIZADA CORRECTAMENTE" + "Mensaje" +JOptionPane.INFORMATION_MESSAGE);
        
        }catch ( PublicacionException | BibliotecaException pe){
        JOptionPane.showMessageDialog(this, "Error formato " + pe.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }catch (NumberFormatException nfe){
           JOptionPane.showMessageDialog(this,"\nError de formato de numérico: " + nfe.toString(),"Mensaje",JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed

    private void jButtonBuscarIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarIconActionPerformed
        // TODO add your handling code here:
        //SELLECCI�N DE IMAGENES SE ABRE EN UN DIRECTORIO DENTRO DEL PROYECTO LLAMADO <posiblesimagenes>
		
         JFileChooser chooser = new JFileChooser("posiblesimagenes");


        int returnVal = chooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {

            jLabelRuta.setText(chooser.getSelectedFile().getPath());//Colocamos la ruta donde esta guardada la imagen original
            //jTextFieldFoto.setText(chooser.getSelectedFile().getName());


            String ruta=jLabelRuta.getText();
            jLabelImagen.setSize(200, 266);
            ImageIcon imagen = new ImageIcon(chooser.getSelectedFile().getPath());//nueva variable imagen de tipo ImagenIcon con el valor de la img seleccionada
            
			//Se redimensiona y se asigna a la var imgRedimensionada.
            ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), 1));
            jLabelImagen.setIcon(imgRedimensionada);//colocamos la imagen en el jLabel.



        }
        
    }//GEN-LAST:event_jButtonBuscarIconActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Fecha;
    private javax.swing.JSpinner FechaLectura;
    private javax.swing.JSpinner FechaLecturaT;
    private javax.swing.JSpinner FechaRevista;
    private javax.swing.JTextArea areaObservaciones;
    private javax.swing.JComboBox comboBoxPublicaciones;
    private javax.swing.JTextField cuadroAutores;
    private javax.swing.JTextField cuadroCalificacionP;
    private javax.swing.JTextField cuadroCalificacionT;
    private javax.swing.JTextField cuadroCodigo;
    private javax.swing.JTextField cuadroColeccion;
    private javax.swing.JTextField cuadroContenido;
    private javax.swing.JTextField cuadroDepartamentoP;
    private javax.swing.JTextField cuadroDepartamentoT;
    private javax.swing.JTextField cuadroEdicion;
    private javax.swing.JTextField cuadroEditorial;
    private javax.swing.JTextField cuadroEntidadP;
    private javax.swing.JTextField cuadroEntidadT;
    private javax.swing.JTextField cuadroIsbn;
    private javax.swing.JTextField cuadroLocalidad;
    private javax.swing.JTextField cuadroLocalizacion;
    private javax.swing.JTextField cuadroLocalizacionR;
    private javax.swing.JTextField cuadroMateria;
    private javax.swing.JTextField cuadroNumero;
    private javax.swing.JTextField cuadroPaginas;
    private javax.swing.JTextArea cuadroProgramaT;
    private javax.swing.JTextField cuadroPublicacion;
    private javax.swing.JTextField cuadroTitulacionP;
    private javax.swing.JTextField cuadroTitulo;
    private javax.swing.JTextField cuadroTribunalP;
    private javax.swing.JTextField cuadroTribunalT;
    private javax.swing.JTextField cuadroVolumen;
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonBuscarIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelRuta;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JPanel jPanelLibro;
    private javax.swing.JPanel jPanelProyecto;
    private javax.swing.JPanel jPanelPublicacion;
    private javax.swing.JPanel jPanelRevistas;
    private javax.swing.JPanel jPanelTesis;
    private javax.swing.JPanel jPanelTiposFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox listaPeriodicidad;
    // End of variables declaration//GEN-END:variables
}
